// <auto-generated />
using Jobify.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jobify.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240119143806_addPunaToDb")]
    partial class addPunaToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jobify.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Full-Stack"
                        });
                });

            modelBuilder.Entity("Jobify.Models.Punet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kerkesat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokacioni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Punet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fullstack",
                            Kerkesat = "Shume",
                            Lokacioni = "Prishtine",
                            Name = "Full-Stack"
                        },
                        new
                        {
                            Id = 2,
                            Description = "bakcend",
                            Kerkesat = "Kogja",
                            Lokacioni = "Prishtine",
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 3,
                            Description = "devops",
                            Kerkesat = "Pak",
                            Lokacioni = "Prishtine",
                            Name = "DevOps"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
