// <auto-generated />
using Jobify.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Jobify.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Jobify.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Backend"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Full-Stack"
                        });
                });

            modelBuilder.Entity("Jobify.Models.Punet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kerkesat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lokacioni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Punet");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Përshkrimi 1",
                            Kerkesat = "Kërkesat 1",
                            Lokacioni = "Lokacioni 1",
                            Name = "Punë 1",
                            kategoria = "Administrate"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Përshkrimi 2",
                            Kerkesat = "Kërkesat 2",
                            Lokacioni = "Lokacioni 2",
                            Name = "Punë 2",
                            kategoria = "Teknologji"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Përshkrimi 3",
                            Kerkesat = "Kërkesat 3",
                            Lokacioni = "Lokacioni 3",
                            Name = "Punë 3",
                            kategoria = "Biznis"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
